### cadastrar um usuario
POST http://localhost:4000/auth/cadastrar
Content-Type: application/json

{
    "nome": "Emilia",
    "email": "emilia@gmail.com",
    "senha": "123456"    
}

### logar um usuario
# @name login
POST http://localhost:4000/auth/logar
Content-Type: application/json

{
    "email": "emilia@gmail.com",
    "senha": "123456"    
}

### token
@token = {{login.response.body.token}}


###Pegar todos as despesas
GET http://localhost:4000/despesas
Authorization: Bearer {{token}}


### Criar despesas
POST http://localhost:4000/despesas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Conta de água",
    "valor": 50,
    "pago": false,
    "data": "2000-01-01T00:00:00.000Z"
}

### id de teste
@id=4ae08e88-12c3-4d77-ab64-7659e3a2e988

### Pegar uma despesa pelo id
GET http://localhost:4000/despesas/{{id}}
Authorization: Bearer {{token}}


### Atualizar a despesa pelo id
PATCH  http://localhost:4000/despesas/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Conta de água"
}

### Deletar despesas
DELETE  http://localhost:4000/despesas/{{id}}
Authorization: Bearer {{token}}
